-- CENTRAL DE ESTUDOS V3
-- Pode ser executado mais de uma vez.

create table if not exists public.study_progress (
  user_id uuid not null references auth.users(id) on delete cascade,
  day integer not null check (day between 1 and 14),
  completed boolean not null default false,
  updated_at timestamptz not null default now(),
  primary key (user_id, day)
);

create table if not exists public.study_notes (
  user_id uuid primary key references auth.users(id) on delete cascade,
  content text not null default '',
  updated_at timestamptz not null default now()
);

create table if not exists public.quiz_results (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  score integer not null check (score >= 0),
  total integer not null check (total > 0),
  percentage integer not null check (percentage between 0 and 100),
  created_at timestamptz not null default now()
);

alter table public.study_progress enable row level security;
alter table public.study_notes enable row level security;
alter table public.quiz_results enable row level security;

grant select, insert, update, delete on public.study_progress to authenticated;
grant select, insert, update, delete on public.study_notes to authenticated;
grant select, insert, delete on public.quiz_results to authenticated;
grant usage, select on sequence public.quiz_results_id_seq to authenticated;

do $$ begin
  create policy "Usuário visualiza próprio progresso" on public.study_progress for select using (auth.uid() = user_id);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "Usuário cria próprio progresso" on public.study_progress for insert with check (auth.uid() = user_id);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "Usuário atualiza próprio progresso" on public.study_progress for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "Usuário exclui próprio progresso" on public.study_progress for delete using (auth.uid() = user_id);
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "Usuário visualiza próprias notas" on public.study_notes for select using (auth.uid() = user_id);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "Usuário cria próprias notas" on public.study_notes for insert with check (auth.uid() = user_id);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "Usuário atualiza próprias notas" on public.study_notes for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "Usuário exclui próprias notas" on public.study_notes for delete using (auth.uid() = user_id);
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "Usuário visualiza próprios simulados" on public.quiz_results for select using (auth.uid() = user_id);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "Usuário salva próprios simulados" on public.quiz_results for insert with check (auth.uid() = user_id);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "Usuário exclui próprios simulados" on public.quiz_results for delete using (auth.uid() = user_id);
exception when duplicate_object then null; end $$;

